services:
  - type: web
    name: brainstormity-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn BrainstormityBrain.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: HUGGINGFACE_API_KEY
        sync: false