name: Test Before Deploy

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test API startup
      run: |
        # Test that the app can start without errors
        timeout 10s python -c "
        import sys
        sys.path.append('BrainstormityBrain')
        from main import app
        print('✅ App imports successfully')
        " || echo "❌ App failed to import"
    
    - name: Check for syntax errors
      run: |
        python -m py_compile BrainstormityBrain/main.py